### ISSUE TITLE
Support NodeJS 14

### ISSUE THREAD

**Issue by kallaspriit** [RobotWebTools/rclnodejs-cli#17]
Hey, any reason for not supporting the current LTS NodeJS 14, should probably work just fine?

Also the link to the project in rclnodejs package is wrong in "rclnodejs-cli is a companion project we recently launched to provide.." text.

**Comment by wayneparrott** [comment]
The plan is to update to use the latest rclnodejs 0.21 with node16 level support as well as update to the latest TypeScript 4.X version.

**Comment by wayneparrott** [comment]
Closing. Release 0.2.0 can now be run with node v10-17 similar to the latest rclnodejs 0.21.
