### ISSUE TITLE
colcon dependency

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/rclnodejs-cli#8]
New CI infrastructure in PR #7 is failing because of a `colcon` dependency.

The initial implementation of the package-creation tool is heavily dependent upon ros2 package design and tooling. After seeing the CI fail due to `colcon` not being installed, it seems I may have over reached in how I designed and impl'ed the package-creation tool with core ros2 dependencies. I prematurely locked in on my ultimate vision for being able to create nodejs modules that are compatible ros2 packages and work with the ros2 cli tools. The current tooling can do this very well but requires a full install of ros2 tools including colcon for building ros2 packages.

I can see value in a simple project setup tool with no ros2 package dependencies. 

With that I'm thinking we should revise the package-creation tool such that it's basic features will create a simple nodejs package configured with rclnodejs and an optional example. It's optional advanced features would setup a ros2 package on top of the newly created rclnodejs nodejs package as they do now. There would be no `colcon` dependencies.

@minggangw  thoughts?

**Comment by minggangw** [comment]
I think it's reasonable that the developers have a full install of ROS2 if they want to run a ROS2 app.

**Comment by wayneparrott** [comment]
deferring for the near term. Will reopen in the future if needed.
